left_arm_traj_controller:
  joints:
    - "l_arm_shz"
    - "l_arm_shx"
    - "l_arm_ely"
    - "l_arm_elx"
    - "l_arm_wry"
    - "l_arm_wrx"
    - "l_arm_wry2"
right_arm_traj_controller:
  joints:
    - "l_arm_shz"
    - "l_arm_shx"
    - "l_arm_ely"
    - "l_arm_elx"
    - "l_arm_wry"
    - "l_arm_wrx"
    - "l_arm_wry2"